### PR TITLE
Add support for NS-3.41

### PR DESCRIPTION
**Pull request by a-andre**

### CODE REVIEW

**Comment by Filip2142** [comment]
Is it works? I got some errors with satellite modul:

[258/2378] Building CXX object contrib/satellit...satellite-obj.dir/helper/simulation-helper.cc.o
FAILED: contrib/satellite/CMakeFiles/libsatellite-obj.dir/helper/simulation-helper.cc.o 
/usr/bin/ccache /usr/bin/c++ -DHAVE_BOOST -DHAVE_BOOST_UNITS -DHAVE_GSL -DHAVE_LIBXML2 -DHAVE_SQLITE3 -DNS3_ASSERT_ENABLE -DNS3_BUILD_PROFILE_DEBUG -DNS3_LOG_ENABLE -DPROJECT_SOURCE_PATH=\"/home/filip/ns-allinone-3.41/ns-3.41\" -D__LINUX__ -I/home/filip/ns-allinone-3.41/ns-3.41/build/include -I/usr -I/usr/include/freetype2 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gtk-3.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/libxml2 -g -fPIC   -fno-semantic-interposition -fdiagnostics-color=always -Wall -Werror -Wno-error=deprecated-declarations -std=c++20 -Winvalid-pch -include /home/filip/ns-allinone-3.41/ns-3.41/cmake-cache/CMakeFiles/stdlib_pch-debug.dir/cmake_pch.hxx -MD -MT contrib/satellite/CMakeFiles/libsatellite-obj.dir/helper/simulation-helper.cc.o -MF contrib/satellite/CMakeFiles/libsatellite-obj.dir/helper/simulation-helper.cc.o.d -o contrib/satellite/CMakeFiles/libsatellite-obj.dir/helper/simulation-helper.cc.o -c /home/filip/ns-allinone-3.41/ns-3.41/contrib/satellite/helper/simulation-helper.cc
/home/filip/ns-allinone-3.41/ns-3.41/contrib/satellite/helper/simulation-helper.cc: In member function ‘void ns3::SimulationHelper::SetErrorModel(ns3::SatPhyRxCarrierConf::ErrorModel, double)’:
/home/filip/ns-allinone-3.41/ns-3.41/contrib/satellite/helper/simulation-helper.cc:997:19: error: comparison of floating-point type ‘double’ with enumeration type ‘ns3::SatPhyRxCarrierConf::ErrorModel’ is deprecated [-Werror=deprecated-enum-float-conversion]
  997 |     if (errorRate == SatPhyRxCarrierConf::EM_CONSTANT)
      |         ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors

Thanks a lot.

**Comment by a-andre** [comment]
You will get the same error with NS 3.40 if you treat all warnings as errors.

The `deprecated-enum-float-conversion` warning should be fixed in a separate PR as it is unrelated to the NS update.

**Comment by Filip2142** [comment]
Thanks for you answer. What do you mean: separate PR? And when it will be released? Thank you for your work!

**Comment by yeliqseu** [comment]
You may pass --disable-werror when configure, to let ns3 not treat warning as errors.

**Comment by Filip2142** [comment]
I tried --disable-werror but after running examples from satellite module got this error:
[0/2] Re-checking globbed directories...
ninja: no work to do.
msg="SatEnvVariables::LocateDirectory - Directory not found within 10 levels: contrib/satellite/data/sims", file=/home/filip/ns-allinone-3.41/ns-3.41/contrib/satellite/utils/satellite-env-variables.cc, line=374
NS_FATAL, terminating
terminate called without an active exception
Command 'build/contrib/satellite/examples/ns3.41-sat-constellation-example-debug' died with <Signals.SIGABRT: 6>.

**Comment by bastientauran** [comment]
Module has been updated for version ns-3.41 in commit 8221cdbb1953e41e65d0cad4c9ee80862bab9133.
Issue #52 fixed too.

**Pull request closed without merging**
